data_args:
  file_path: data
dataloader_args:
  batch_size: 128
  num_workers: 4
  shuffle: true
model_args:
  critic_args:
    activation: gelu
    num_channels:
    - 16
    - 32
    - 64
    - 128
    - 256
    num_dense_neurons:
    - 256
    - 128
    resnet: false
    wasserstein: true
  generator_args:
    activation: gelu
    latent_dim: 100
    num_channels:
    - 256
    - 128
    - 64
    - 32
    - 16
    num_dense_neurons:
    - 128
    - 256
    resnet: false
    transposed_conv: False,
optimizer_args:
  learning_rate: 1.0e-05
  scheduler_args:
    args:
      T_max: 2000
    type: cosine
  weight_decay: 1.0e-06
train_stepper_args:
  gradient_penalty_regu: 10.0
  num_critic_steps: 1
  wasserstein: true
trainer_args:
  num_epochs: 2000
