data_args:
  file_path: data
dataloader_args:
  batch_size: 4
  num_workers: 4
  shuffle: true
model_args:
  critic_args:
    activation: gelu
    num_channels:
    - 16
    - 32
    - 64
    - 128
    num_dense_neurons:
    - 128
    - 64
  generator_args:
    activation: gelu
    num_channels:
    - 8
    - 16
    - 32
    - 64
    - 128
    num_dense_neurons:
    - 64
    - 128
optimizer_args:
  learning_rate: 0.0005
  scheduler_args:
    args:
      factor: 0.9
      min_lr: 1.0e-06
      patience: 10
    type: plateau
  weight_decay: 1.0e-08
train_stepper_args:
  GAN_regularization: 0.001
  gradient_penalty_regu: 10.0
  num_critic_steps: 1
  with_GAN_loss: false
trainer_args:
  num_epochs: 1000
