data_args:
  file_path: data
dataloader_args:
  batch_size: 16
  num_workers: 16
  shuffle: true
model_args:
  generator_args:
    activation: gelu
    num_channels:
    - 32
    - 64
    - 128
    - 256
    num_dense_neurons:
    - 64
    - 128
optimizer_args:
  learning_rate: 0.0001
  scheduler_args:
    args:
      T_max: 5000
    type: cosine
  weight_decay: 1.0e-06
train_stepper_args:
  num_steps: 1
trainer_args:
  num_epochs: 5000
