data_args:
  file_path: 'data'

dataloader_args:
  batch_size: 10
  num_workers: 1
  shuffle: True

model_args:
  fno3d_args:
    modes1: 16
    modes2: 16
    modes3: 16
    width: 64
    padding: 4
    input_channels: 4

    
optimizer_args:
  learning_rate: 5.0e-4
  weight_decay: 1.0e-8
  scheduler_args:
    type: 'plateau'
    args:
      patience: 10
      factor: 0.9
      min_lr: 1.0e-6
  #     #warmup: 10
  #     #total_steps: 1000

train_stepper_args:
  model_save_path: 'trained_models/FNO3D'


trainer_args:
  num_epochs: 1000
