data_args:
  file_path: 'data'

dataloader_args:
  batch_size: 4
  num_workers: 2

model_args:
  generator_args:
    latent_dim: 16
    num_dense_neurons: [4, 8, 16, 32]
    num_channels: [16, 8, 4]
    activation: 'gelu'
  critic_args:
    num_dense_neurons: [4, 8, 16]
    num_channels: [4, 8, 16, 32]
    activation: 'gelu'
  
optimizer_args:
  learning_rate: 1.0e-3
  weight_decay: 1.0e-8
  scheduler_args:
  #  type: 'plateau'
  #  args:
  #    patience: 10
  #    factor: 0.5
  #    min_lr: 1.0e-6

  
train_stepper_args:
  gradient_penalty_regu: 1.0e-2
  num_critic_steps: 5

trainer_args:
  num_epochs: 100
