data_args:
  file_path: 'data'

dataloader_args:
  batch_size: 16
  num_workers: 16
  shuffle: true

model_args:
  generator_args:
    latent_dim: 250
    num_dense_neurons: [256]
    num_channels: [64, 32, 16, 8, 4]
    activation: 'leaky_relu'
    transposed_conv: True,
    resnet: False
  critic_args:
    num_dense_neurons: [256]
    num_channels: [4, 8, 16, 32, 64]
    activation: 'leaky_relu'
    resnet: False
  
optimizer_args:
  learning_rate: 5.0e-5
  weight_decay: 1.0e-7
  scheduler_args: null
  #  type: 'plateau'
  #  args:
  #    patience: 10
  #    factor: 0.5
  #    min_lr: 1.0e-6

train_stepper_args:
  gradient_penalty_regu: 10.0
  num_critic_steps: 3

trainer_args:
  num_epochs: 30000
