data_args:
  file_path: 'data'

dataloader_args:
  batch_size: 128
  num_workers: 4
  shuffle: true

model_args:
  generator_args:
    latent_dim: 100
    num_dense_neurons: [128, 256]
    num_channels: [256, 128, 64, 32, 16]
    activation: 'gelu'
    transposed_conv: False,
    resnet: False
  critic_args:
    num_dense_neurons: [256, 128]
    num_channels: [16, 32, 64, 128, 256]
    activation: 'gelu'
    resnet: False
    wasserstein: True
  
optimizer_args:
  learning_rate: 1.0e-5
  weight_decay: 1.0e-6
  scheduler_args:
    type: 'cosine'
    args:
      T_max: 2000

train_stepper_args:
  gradient_penalty_regu: 10.0
  num_critic_steps: 1
  wasserstein: True

trainer_args:
  num_epochs: 2000
