data_args:
  file_path: 'data'

dataloader_args:
  batch_size: 8
  num_workers: 4
  shuffle: True

model_args:
  num_dense_neurons: [64, 128]
  num_channels: [32, 64, 128, 256] #[128, 64, 32, 16, 8]
  activation: 'gelu'
  
optimizer_args:
  learning_rate: 1.0e-4
  weight_decay: 1.0e-6
  scheduler_args:
    type: 'cosine'
    args:
      T_max: 5000
      #patience: 100
      #factor: 0.9
      #min_lr: 1.0e-6
      #warmup: 25
      #total_steps: 2000

train_stepper_args:

trainer_args:
  num_epochs: 5000
