data_args:
  file_path: 'data'

dataloader_args:
  batch_size: 16
  num_workers: 16
  shuffle: True

model_args:
  generator_args:
    num_dense_neurons: [64, 128]
    num_channels: [32, 64, 128, 256] #[128, 64, 32, 16, 8]
    activation: 'gelu'
  
optimizer_args:
  learning_rate: 1.0e-4
  weight_decay: 1.0e-6
  scheduler_args:
    type: 'cosine'
    args:
      T_max: 5000

train_stepper_args:
  num_steps: 1

trainer_args:
  num_epochs: 5000
