data_args:
  file_path: 'data'

dataloader_args:
  batch_size: 32
  shuffle: True
  num_workers: 16

model_args:
  decoder_args:
    latent_dim: 200
    num_dense_neurons: [256]
    num_channels: [128, 64, 32, 16, 8]
    activation: 'leaky_relu'
    transposed_conv: True,
    resnet: False
  encoder_args:
    latent_dim: 200
    num_dense_neurons: [256]
    num_channels: [8, 16, 32, 64, 128]
    activation: 'leaky_relu'
    resnet: False
  
optimizer_args:
  learning_rate: 5.0e-4
  weight_decay: 1.0e-8
  scheduler_args:
    type: 'plateau'
    args:
      patience: 25
      factor: 0.9
      min_lr: 1.0e-6

train_stepper_args:
  MMD_regu: 1.0e-2

trainer_args:
  num_epochs: 30000
